language: 
- node_js
- java
node_js:
- "node"
dist: trusty
addons:
 sonarcloud:
   organization: "$SONAR_ORGANIZATION"
   token:
     secure: "$SONAR_TOKEN"
script:
# instalar dependências
- npm install
# Testes
- npm run test
- npm run test:cov
# análise de qualidade de código
- sonar-scanner